let text = `
Căn hộ nằm trên tầng ba, kế cầu thang thoát hiểm. Lần cuối Huyền đứng trước cửa với chùm chìa khóa trong tay, cặp đèn huỳnh quang trên đầu vẫn còn cháy một cái và hình con mèo cầm liễn “Cung Chúc Tân Xuân” thì vẫn còn cái liễn.
        	“Năm nay năm con Rồng mà mẹ?”
        	Thằng Trường con chị buột miệng hỏi. Nghe tiếng chuột kêu dậy lên từ góc tối, bàn tay đẫm mồ hôi của nó lún sâu hơn vào tay chị, tay còn lại không biết làm gì đành nhàu chiếc quần mới ủi đến nhăn nhúm. Trống ngực Huyền khơi dậy trong chị một cảm giác khó chịu vu vơ. Năm đầu đi chúc Tết như vầy thì năm sau làm sao nó dám đi nữa? Huyền thở dài, cảm thấy cả hai thật nực cười và tội nghiệp. 
        	“Chắc ngoại quên đó con, kệ đi.” Tra chìa vào cửa hoài không được, tay Huyền buông tay con để bóp chặt vào cái ống khóa đang lung lay như sắp rớt ra. “Hồi nãy mẹ dặn gì nói lại nghe coi?”
“Dạ.. Một là không đụng vào đồ của bà ngoại, còn hai là... là...”
        	“Ngoại với mẹ nói con mèo ở đâu thì con mèo ở đó.” Tiếng chìa khóa kêu “cạch” một cái, Huyền từ từ đẩy cánh cửa mở ra. Cả hai lập tức nhăn mặt.
        	Mùi sữa thiu. Một tô đầy sữa đã ngả vàng đục đặt ngay ngắn trong góc cửa. Huyền khịt mũi một cái thật mạnh để tống hết kinh tởm trong người ra rồi bước lên bậc thềm, tay kéo theo thằng nhóc vẫn còn đang đứng hình.
        	Đủ loại báo chí sách vở áp phích thủng lỗ chỗ chất tràn lan dọc khoảng hành lang hẹp dẫn vào gian chính, trên sàn nhà, trên cái giá sách gãy một chân, trên cái TV hộp đã đứt bóng từ tám năm trước, trên và dưới bộ bàn ghế bằng nhựa rẻ tiền từng xài để tiếp khách, ém dưới và trong một đống hộp toàn cassette và đĩa nhạc cũ. Dán kín mít trên tường là tranh ảnh về mèo, từ bức vẽ chì sáp nguệch ngoạc của Huyền hồi mẫu giáo tới hình chụp cắt ẩu từ mấy cuốn tạp chí thú cưng, lâu lâu đan vào mấy tiêu đề tạp chí xé phạm về những giống mèo nên nuôi nhất hay cuộc thi sắc đẹp mèo tổ chức ở đâu đó trên Sài Gòn. Ở bức tường khuất khỏi cửa ra vào là một người đàn bà tóc hoa râm xõa ngang vai trong bộ đồ tôn nâu nhạt họa tiết bông đang lúi húi dán lại miếng quảng cáo đồ ăn cho mèo. Miếng quảng cáo dán lên cứ tróc ra; cố một hồi vẫn không được, bà đứng buông thõng hai tay nhìn nó bay lất phất mỗi khi cây quạt trần thổi tới. Nắng sáng lọc qua cái màn cửa sổ phủ lên mọi thứ một màu xanh tái nhợt.
        	“Thưa... thưa bà con mới tới!”
        	Chỉ có tiếng quạt kêu cót két.
        	“Mẹ. Nay mùng Hai, con đưa thằng Trường qua thăm...” Huyền bỏ lửng câu nói, rồi cẩn thận bỏ một chồng báo lên bàn, chị ra hiệu cho thằng nhóc ngồi xuống cái ghế đẩu vừa dọn.
        	“Coi chừng! Con Cọp!”
        	Trong một giây lơ đãng của cả hai, mẹ Huyền chợt quay lại và rú lên. Trường giật thót, xém chút nữa là té đập mặt vào góc bàn nếu chị không kịp đỡ. Bà mẹ chạy lại cái ghế, quỳ xuống ẵm một bụm không khí trên mặt ghế vào trong lòng mà vuốt ve.
“Ngoan, ngoan, ngoại thương, không sao hết phải không, nó làm con giật mình hả, đúng là...” Rồi bà quay ngoắt qua thằng bé. “Mù hả! Đi đứng cho đàng hoàng!”
        	Nhìn Trường mếu khóc tới nơi trốn ra sau lưng mình, Huyển thấy như cục tức đè nén trong bụng từ lúc đứng ở cửa sắp nổ tung ra và trút vào từng mạch máu chị thứ giận dữ tanh tưởi để hòa tan với bản năng người mẹ đang dâng trào thành một cảm xúc bất hiếu không tên; chị nuốt nước miếng cái ực cố gắng đè nó xuống thật sâu, sâu nữa, càng sâu càng tốt. Bình tĩnh lại, tao ơi, bước đầu tiên là gì?
        	“Trường nó còn nhỏ, không có ý tứ gì hết. Trường, xin lỗi bà đi con!” Chị đẩy đứa con mình ra trước mặt mà thấy như vừa xoáy một lưỡi dao vào ngực; hai chân ghim xuống sàn nhà, thằng nhóc vừa quẹt nước mắt nước mũi vừa rặn cho tròn chữ câu “Xin lỗi bà”. Khốn nạn, sao nó giống ba nó dữ vậy, Huyền chột dạ. Hồi trước đã có lần anh giàn giụa ú ớ y thế này với chị.
Đợi nếp nhăn nơi đuôi mắt mẹ mình giãn ra một chút, Huyền triển khai bước tiếp theo của kế hoạch mà chị đã cố vẽ nên trong đêm mất ngủ hôm qua. Chị “Á!” một cái thật to, lùi lại mấy bước như phải đỡ vật gì vừa nhảy lên người, rồi quay người thật chậm qua bàn tiếp khách, chị khom xuống để khuỷu tay vừa chạm mặt bàn, mắt lướt một dọc từ ngực lên cái kệ sách cặp sát tường, nơi vẫn còn một khe hở bằng một gang tay.
“Ui, con Cọp quậy quá ha! Trường, lại xin lỗi bé mèo đi con. Ở chỗ trống ngăn dưới cùng của cái kệ sách đó!” Vẫn khom người, chị kéo thằng Trường về phía mình, chỉ tay về cái kệ và hạ giọng. “Nhớ lời mẹ dặn không?” 
Đợi thằng bé diễn cho khớp vai, chị quay lại phía mẹ - người vẫn nhìn vào lòng, ngơ ngác chưa biết chuyện gì xảy ra – và ngồi chồm hổm đối diện bà.
“Kìa, con Cọp chịu cho thằng Trường nựng rồi kìa! Nó hết giận rồi đó!”
Từng thớ cơ trên gương mặt bà cụ chùn lại khi nghe tới chữ “hết giận,” rồi từng chút một, chúng kéo những nếp nhăn trên đôi gò má xương xẩu đầy tàn nhang vểnh lên – một nụ cười. Ôi, Huyền thở phào, phải lúc nào mẹ cũng giống vầy thì còn gì bằng! Chị mở túi xách, rút ra một bao lì xì đỏ đậm, rộng vừa bàn tay, cẩn thận đưa nó vào tầm nhìn của mẹ.
“Mẹ, con biết mẹ không ưa gì thằng nhỏ, nhưng mà bữa nay là mùng Hai, sinh nhật nó nữa, mẹ lì xì cho nó một lần được không. Tiền con để trong đó sẵn rồi, mẹ chỉ cần đưa nó thôi. Dù gì cũng là…”
Càng thì thầm, Huyền thấy như càng đưa mẹ trở về cõi trần. Chị còn đang phân vân không nên biết dùng từ “gia đình” hay không thì bà cụ gắt ầm lên.
“Mắc gì tao phải đưa. Tao có bao giờ nhận nó là cháu tao đâu!”
“Mẹ, con xin mẹ, đừng có như vậy-”
“Mày đừng có nói với tao chuyện con cháu, cái đồ cãi cha cãi mẹ. Tao chưa bao giờ chấp nhận thằng Thuận làm chồng mày! Mẹ nó, đừng làm tao nhắc tới thằng đó, cái thằng trời đánh, cướp con tao xong bỏ nó giữa đường-”
“Ảnh bị ung thư chết! Nói bao nhiêu lần rồi!” Tới lượt Huyền gắt. Cục tức của chị nổ tung như bong bóng bị kiếng bể găm vào, dịch nhầy của nó dìm mất cái kể hoạch tỉ mỉ của chị. 
“Tao không quan tâm, nó là thằng dụ dỗ mày! Ha, chỉ có thể là quả báo, không gì hơn! Còn mày nữa, trời ơi, sao tôi lại đẻ ra cái thứ bất hiếu này, mới hai mốt tuổi đầu đã bỏ theo trai. Cái đồ vô tâm, mày thèm trai tới nỗi nỡ bỏ… bỏ.... con Cọp hả? Ban đầu chính mày lụm nó về nuôi mà, rồi tao cũng phải nuôi nó chung với mày, rồi lúc không cần nữa, mày lại quăng cái cục nợ đó cho tao. Tại sao mày... mày...” Bà mẹ không nói nổi nữa giữa những cơn nấc. 
Huyền ngạc nhiên; mọi cuộc cãi vã từ lúc chị rời khỏi nhà đều dẫn về đây, và những lời tiếp theo, như mọi khi, cũng đã đập nát những gì còn sót lại của trái tim chị tới mức không còn gì để đập, nhưng đây là lần đầu chị thấy bà khóc. Chị im lặng nhìn từng giọt nước mắt kẹt lại giữa mê cung nếp nhăn dưới hốc mắt bà. Làm sao chị có thể giải thích với một bà góa căm thù đàn ông, một nội trợ suốt đời chỉ quan tâm chuyện nước rửa chén này nhiều bọt hơn nước rửa chén kia, và trên hết, một người mẹ làm ba công việc vì căn nhà bằng cái hộp và đứa con sống trong đó, rằng có ngày nó cũng phải rời cái hộp đó để coi ngoài kia còn có gì khác? Huyền ngồi bệt xuống nền nhà đầy giấy báo cũ. Chậm rãi và gần như vô thức, tay chị vươn ra lau nước mắt cho mẹ, từng ngón miết nhẹ theo những nếp nhăn. Tiếng tích tắc của đồng hồ ngoài hành lang xa dần. 
“Có một kiểu thương, thương một người chỉ vì mình thương người đó, không vì trách nhiệm hay gì hết, mẹ hiểu không… Con biết hồi xưa trước khi cưới ổng mẹ sẽ hiểu, nhưng giờ thì chắc mẹ không hiểu nổi đâu, con cũng không hi vọng mẹ hiểu…” Mày đang lảm nhảm gì vậy, Huyền nghĩ thầm và nhanh chóng chốt lại vấn đề. “Làm sao sống nổi nếu cả đời chết mòn trong một cái hộp, người ta cứ hở ra là hù dọa từ mặt mình. Nói chung là, nếu mẹ cứ không nhận thằng Trường thì con xin phép-” 
Huyền đang rụt tay về thì giật mình vì giữa chừng vì bị bàn tay một mặt đầy đồi mồi, mặt kia đầy vết chai của mẹ nắm chặt.
“... Đưa tao.”
Tức khắc, bao lì xì đổi chủ. Huyền thấy trong cái giật của mẹ còn bỏ ngỏ một sự bất bình, nhưng chưa kịp mở miệng kêu tên con thì khúc mắc đã được giải đáp. Bà mẹ chỉ tay về cái kệ sách.
“Tao chỉ làm nếu mày đi xin lỗi con Cọp. Cho tất cả những chuyện mày đã làm… với nó.”
Lòng Huyền vừa dịu đi chút đỉnh lại gợn nhẹ. Hay thiệt, thế là chị phải tự mình diễn cho tròn vai cái vở kịch đã tự biên soạn. Chị kêu thằng Trường ẵm con mèo qua chỗ mình. Không có tiếng trả lời. Chị nhìn qua khoảng trống giữa bàn tiếp khách: thằng nhóc vẫn còn nhập tâm quá, bóng lưng nó vẫn ôm trọn cái khoảng trống của kệ sách, chắc đang ghiền đọc một cuốn truyện cũ nào đó của chị. Bực mình, Huyền đứng phắt dậy, sải ba bước tới chỗ thằng bé, kéo nó ra, và đứng chết trân khi thấy có con mèo, đúng, thực sự có con mèo lông cam vằn đen với một chân trắng nằm ườn ra trên kệ. Thấy chị, nó “meo” một tiếng rõ lớn rồi há miệng ngáp.
Con Cọp. 
Mình điên rồi à, Huyền dụi mắt thật lâu, nhìn xung quanh, và nhìn cái kệ một lần nữa; con mèo vẫn ở đó. Việc đầu tiên chị nghĩ tới là mẹ mình tuyệt vọng quá đã bắt mèo hoang về rồi giả bộ nó là con Cọp, nhưng giả sao được mấy vết sẹo dọc mạng sườn con mèo, thứ đã ở đó ngay từ ngày chị lụm được nó từ một cái hộp các-tông trong đống rác trên đường đi học, và cái vòng cổ giả da màu hồng, trên cùng có chữ “HỔ” viết tỉ mỉ bằng bút lông dầu, mẹ chị phải mất một buổi chiều chạy khắp chợ mới mua được.
“Tr...Trường... “ Huyền khàn giọng hỏi, “con mèo, con Cọp, sao nó ở đây?”
“Con mèo nào hả mẹ?” Thằng nhóc tỉnh bơ dập tắt nỗ lực cuối cùng để bám víu vào thực tại của Huyền. Giấy dán trên bốn bức tường và rải khắp sàn chảy ra, quện vào nhau đặc sệt thành một thứ màu be nhạt. Thứ chất đó trôi tuột khỏi tường, chừa lại một mảnh giấy duy nhất có hình con mèo lông cam vằn đen với một chân trắng in màu cùng dòng chữ tiêu đề quá khổ:
“TÌM MÈO LẠC.”
Trước mặt chị chỉ còn con Cọp đang lim dim. Huyền từ từ ngồi xuống như sợ con mèo giật mình chạy mất. Chị nhắm mắt, giơ một ngón tay ra chạm lên đỉnh đầu con mèo tưởng tượng.
Mịn màng, một chút gồ ghề. Ấm. Rồi cảm giác lan từ đầu ngón tay ra khắp lòng bàn tay, làm Huyền giật mình mở mắt. Con Cọp dụi đầu vào tay chị, miệng rên “gừ gừ” như muốn khuyến khích chị tiếp tục.
“Xin lỗi em. Lúc em đi lạc, chị còn không hay.” Một giọt nước mắt chảy vào khóe môi Huyền, rồi thêm một giọt, một giọt nữa. “Anh Thuận bị dị ứng với lông mèo, nên chị muốn để mẹ có bạn khi chị... Đáng lẽ chị không nên bỏ em lại. Chị chưa bao giờ muốn bỏ em hết! Xin lỗi em, Cọp!”
Con Cọp nằm im để Huyền vừa vuốt ve khắp mình vừa trút hết những lời biện minh ra, thỉnh thoảng liếm liếm tay Huyền khi nó ghé qua đầu. Lần cuối chị cảm nhận được cái mềm mại, ấm áp và ươn ướt này, là ngày chị học được cách phớt lờ câu “Tao từ mặt mày” của mẹ để thông báo việc mình sẽ dọn ra ở với chồng. Đêm đó, khi rúc mình vào đống va li và túi xách để giả ngủ, con Cọp cũng quấn lấy mà liếm láp khuôn mặt tèm lem nước mắt nước mũi của Huyền như thế này, tới khi nào chị cười mới thôi, rồi lại chui vào lòng người mẹ mới xong ca đêm về ngồi sụt sùi canh cửa để làm điều tương tự. 
Cơn lũ ký ức chở chị về xa hơn, trước khi chị say đắm một đàn anh đại học hào hoa tên Thuận, trước cả khi chị biết yêu ai đó là gì, để Huyền sống lần nữa cái thời mà khái niệm duy nhất về “hạnh phúc” được gói gọn trong chiếc hộp sáu mươi mét khối với một người phụ nữ ngoài năm mươi và một con mèo. 
Rồi Huyền chìm trong suy nghĩ về người phụ nữ. Trước chị, trước cái hộp, bà đã “thương” như thế nào nhỉ? Chỉ có một tình yêu cuồng dại, Huyền biết rõ, thì khi mục rữa đi mới biến thành thứ thù hằn cay nghiệt đến thế. Đã vậy, tại sao lại đổ hai mươi mốt năm tự do vào sản phẩm thừa của một cuộc tình chết yểu vì thói đời? Chỉ là trách nhiệm, hay còn lí do nào… 
Một giọng nói kéo Huyền về đất liền.
“Mẹ ơi mẹ, mẹ có sao không mẹ?” Thấy chị khóc, Trường quýnh quá làm rớt bao lì xì trong tay xuống đất, không hiểu chuyện gì xảy ra nên cũng sắp mếu theo. Huyền vội lấy tay áo chùi mặt và kèm theo cái lắc đầu một nụ cười trấn an. Chị quay lại cái góc kệ sách. Trống trơn: con Cọp đã biến mất đột ngột như cách nó xuất hiện. Sau lưng chị, khuất khỏi bộ bàn ghế, mẹ vẫn ngồi xếp bằng, dỗ dành nâng niu một vật gì đó không rõ. Trong khoảnh khắc vô tận cuối cùng trước khi thời gian trong hộp trôi trở lại, Huyền thấy mắt mẹ sáng lên, không rõ do nước mắt hay ánh đèn hắt xuống.
Vẫn ngồi sụp xuống, Huyền ngước nhìn Trường hồi lâu, thấy sao sự lúng túng của nó dễ thương quá chừng, không kìm nổi phải nhéo má thằng nhóc một cái, mỉm cười, nhìn mẹ lần nữa, và để ý bà cũng đang cười giống mình. Giống anh Thuận nữa, lúc anh nằm trên giường bệnh và thống nhất với chị sẽ đặt tên con là gì. Và chị nhận ra.
Tất cả đều cười nụ cười của những kẻ quẫn trí vì yêu.
Huyền nhớ đã từng đọc về giả thuyết của một nhà vật lí nào đó rằng, khi ta bỏ con mèo vào cái hộp rồi đậy kín thì sẽ không biết được nó sống hay chết cho tới khi mở nắp hộp ra. Có lẽ nếu ông còn sống, chị sẽ tới gặp, hay viết thư cho ông để thông báo rằng, thưa ông, thực tại còn kỳ lạ hơn thế nữa, vì có những cái hộp khi đã xé bung ra vẫn không biết con mèo bên trong như thế nào.
“Mai con đưa thằng Trường qua nội, rồi con ở đây vài bữa.” Chậm rãi và gần như vô thức, miệng chị ngập ngừng bật mở những câu từ gạn được từ một tâm trí vừa lặng sóng. “Để dọn nhà.”
Có lẽ chị sẽ nói thêm với ông, như vậy có khi cũng tốt.
`;


console.log(JSON.stringify(text));